# -*- coding: utf-8 -*-
"""firstdatabig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkkCNe0qH2vTmGJqMLDi6_NsFlGeCjzC
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, isnan, when, count
import pandas as pd
from pyspark.sql.functions import split, unix_timestamp,when, col, sum ,year, month, dayofweek, hour
from datetime import time
import plotly.express as px

from google.colab import files
!pip install keplergl
from keplergl import KeplerGl

spark=SparkSession.builder.appName("first big data").getOrCreate()

df_sp1501=spark.read.csv("/content/yellow_tripdata_2015-01.csv", header=True, inferSchema=True)
df_sp1601=spark.read.csv("/content/yellow_tripdata_2016-01.csv", header=True , inferSchema=True)
df_sp1602=spark.read.csv("/content/yellow_tripdata_2016-02.csv", header=True , inferSchema=True)
df_sp1603=spark.read.csv("/content/yellow_tripdata_2016-03.csv", header=True , inferSchema=True)

df_sp=df_sp1501.union(df_sp1601).union(df_sp1602).union(df_sp1603)
df_sp.show(5)

df_sp.select([sum(col(c).isNull().cast("int")).alias(c) for c in df_sp.columns]).show()

df_sp.summary().show()

"""# Yeni Bölüm"""

df_sp.show(5)

df_sp.printSchema()

byk=df_sp.select([count(when(col(c).isNull(),c)).alias(c)for c in df_sp.columns]).show()

df_sp.summary().show()

select=df_sp.select('fare_amount','total_amount')
select.show(5)

flr=df_sp.filter(df_sp['total_amount']<2  )
flr.show(5)

bahsıs=df_sp.orderBy(df_sp['tip_amount'], ascending=True)
bahsıs.show(5)

sıra=df_sp.orderBy(df_sp['tip_amount'], ascending=False)
sıra.show(5)

passenger=df_sp.orderBy(df_sp['passenger_count'], ascending=False)
passenger.show(5)

tip=df_sp.select('tip_amount', 'passenger_count')
tip.show(5)

odemey=df_sp.select("payment_type")
odemey.show(5)

gecıs=df_sp.orderBy(df_sp['tolls_amount'], ascending=False)
gecıs.show(5)

df_sp=df_sp.filter(df_sp["passenger_count"]> 0 )
df_sp.show(10)

df_sp.count()

df_sp =df_sp.withColumn("pickup_datetime", split(df_sp["tpep_pickup_datetime"], " ")[1])\
             .withColumn("dropoff_datetime", split(df_sp["tpep_dropoff_datetime"], " ")[1])

df_sp = df_sp.withColumn("time_different_minute",
                         (unix_timestamp("tpep_dropoff_datetime", "yyyy-MM-dd HH:mm:ss") -
                          unix_timestamp("tpep_pickup_datetime", "yyyy-MM-dd HH:mm:ss")) / 60)


df_sp.select("tpep_pickup_datetime", "tpep_dropoff_datetime", "time_different_minute")

df_sp=df_sp.withColumn("fare_per_minute", col("fare_amount") / col("time_different_minute"))
df_sp=df_sp.withColumn("fare_per_km", col("fare_amount") / col("trip_distance"))





df_sp.show(5)

df_sp=df_sp.withColumn("year", year(df_sp["tpep_pickup_datetime"]))
df_sp=df_sp.withColumn("month", month(df_sp["tpep_pickup_datetime"]))
df_sp=df_sp.withColumn("hour", hour(df_sp["tpep_pickup_datetime"]))
df_sp=df_sp.withColumn("dayofweek", dayofweek(df_sp["tpep_pickup_datetime"]))
df_sp.show(5)

ccoo=df_sp.groupBy("hour").count().toPandas()
fig=px.bar(ccoo , x="hour", y="count", title="hourse ,(tpep_pickup_datetime)")
fig.show()

df_sp=df_sp.withColumn("payment",
                       when(df_sp.payment_type == 1 , "cash")
                    .when(df_sp.payment_type == 2 , "credid card")
                    .otherwise("ı dont know")
                    )

df_sp.show(5)

aa=df_sp.groupBy("payment").count().toPandas()
fig=px.bar(aa, x="payment", y="count")
fig.show()

df_sp=df_sp.withColumn("day_name",

                       when(df_sp.dayofweek == 1, "pazartesı")
                    .when(df_sp.dayofweek == 2 , "salı")
                    .when(df_sp.dayofweek ==  3, "çarşamba")
                    .when(df_sp.dayofweek ==  4, "perşembe")
                    .when(df_sp.dayofweek ==  5, "cuma")
                    .when(df_sp.dayofweek ==  6, "cumartesi")
                    .when(df_sp.dayofweek ==  7, "pazar")
                    .otherwise("bilinmiyor")
                                         )

df_sp.show(5)

df_sp=df_sp.withColumn("dayofweek_d", dayofweek(df_sp["tpep_dropoff_datetime"]))

aa=df_sp.groupBy("day_name").count().toPandas()
fig=px.bar(aa, x="day_name", y="count", title="day_name")
fig.show()

df_sp=df_sp.withColumn("month_string",
                         when(col("month") == 1 , "ocak")
                       .when(col("month")== 2 , "şubat")
                       .when(col("month") == 3 ,"mart")
                       .when(col("month") == 4 ,"nisan")
                       .when(col("month") == 5 , "mayıs")
                       .when(col("month") == 6 , "haziran")
                       .when(col("month") == 7 ,"temmuz")
                       .when(col("month") == 8 , "ağustos")
                       .when(col("month") == 9 , "eylül")
                       .when(col("month") == 10, "ekim")
                       .when(col("month") == 11, "kasım")
                       .when(col("month") == 12, "aralık")
                       .otherwise("try agen")


                       )

df_sp.show(5)


aa=df_sp.groupBy("month_string").count().toPandas()
bb=px.bar(aa, x="month_string" , y="count")
bb.show()

aa=df_sp.orderBy(df_sp["month_string"], ascending=False)
aa.show(5)

df_sp=df_sp.withColumn("year_d", year(df_sp["tpep_dropoff_datetime"]))
df_sp=df_sp.withColumn("month_d", month(df_sp["tpep_dropoff_datetime"]))
df_sp=df_sp.withColumn("hour_d", hour(df_sp["tpep_dropoff_datetime"]))
df_sp=df_sp.withColumn("dayofweek_d", dayofweek(df_sp["tpep_dropoff_datetime"]))


count_d=df_sp.groupBy("hour_d").count().toPandas()
fig=px.bar(count_d, x="hour_d", y="count", title="hours (tpep_dropoff_datetime)" )
fig.show()

count_t=df_sp.groupBy("payment_type").count().toPandas()

fig=px.bar(count_t,x="payment_type" , y="count", title="payment")
fig.show()

count_p=df_sp.groupBy("passenger_count").count().toPandas()

fig=px.bar(count_p, x="passenger_count", y="count", title="passenger")
fig.show()

count_s=df_sp.groupBy("store_and_fwd_flag").count().toPandas()
fig=px.bar(count_s,x="store_and_fwd_flag", y="count" ,title="strove count" )
fig.show()

tt=df_sp.select('pickup_longitude', 'pickup_latitude','dropoff_longitude' ,'dropoff_latitude').dropna().toPandas()

kep=KeplerGl()
kep.add_data(data=tt, name='konum')



kep.save_to_html(file_name="konumları_gor.html")

from google.colab import drive
drive.mount('/content/drive')