# -*- coding: utf-8 -*-
"""firstdatabig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkkCNe0qH2vTmGJqMLDi6_NsFlGeCjzC
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, isnan, when, count
import pandas as pd
from pyspark.sql.functions import split, unix_timestamp
from datetime import time

spark=SparkSession.builder.appName("first big data").getOrCreate()

df_sp=spark.read.csv("/content/sample_data/yellow_tripdata_2015-01.csv",header=True, inferSchema=True)

"""# Yeni Bölüm"""

df_sp.show(5)

df_sp.printSchema()

byk=df_sp.select([count(when(col(c).isNull(),c)).alias(c)for c in df_sp.columns]).show()

df_sp.summary().show()

select=df_sp.select('fare_amount','total_amount')
select.show(5)

flr=df_sp.filter(df_sp['total_amount']<2)
flr.show(5)

bahsıs=df_sp.orderBy(df_sp['tip_amount'], ascending=False)
bahsıs.show(5)

sıra=df_sp.orderBy(df_sp['tip_amount'], ascending=True)
sıra.show(5)

passenger=df_sp.orderBy(df_sp['passenger_count'], ascending=False)
passenger.show(5)

df_sp = df_sp.withColumn("time", split(df_sp["tpep_pickup_datetime"], " ")[1])\
             .withColumn("timee", split(df_sp["tpep_dropoff_datetime"], " ")[1])

df_sp = df_sp.withColumn("time_different_minute",
                         (unix_timestamp("tpep_dropoff_datetime", "yyyy-MM-dd HH:mm:ss") -
                          unix_timestamp("tpep_pickup_datetime", "yyyy-MM-dd HH:mm:ss")) / 60)


df_sp.select("tpep_pickup_datetime", "tpep_dropoff_datetime", "time_different_minute")
df_sp.show(5)

tip=df_sp.select('tip_amount', 'passenger_count')
tip.show(5)

odemey=df_sp.olderBy(df_sp['payment_type'], ascending=False)
odemey.show(5)

gecıs=df_sp.orderBy(df_sp['tolls_amount'], ascending=False)
gecıs.show(5)

from google.colab import drive
drive.mount('/content/drive')